Nodelet-node template utilities
PRX-Kinodynamic/mujoco_ros pull request #23
Opened 2024-03-25 14:35 UTC by garygra

I've had problems debugging nodelets (need restart, crashes other nodelets, etc). In [some](https://answers.ros.org/question/35171/how-to-debug-nodelet-manager-crashes/) discussions, it is suggested to have a common implementation and launch either a node or nodelet depending on need. However, the implementation suggested that it seems convoluted and difficult to maintain.

Adding a utility for implementing nodelets so they can also be run as a simple node straightforwardly. It only requires three steps: 
  * implement nodelet as template on a base class. 
  * Instantiate nodelet using `nodelet::Nodelet`
  * Instantiate node using `utils::nodelet_as_node_t`

2024-03-29 18:36 UTC, aravindsiv requested changes
Thx for the PR - just need some clarifications before we can merge.

2024-03-29 18:36 UTC, aravindsiv commented on world/mujoco_ros/launch/mushr.launch
> +        <node pkg="nodelet" type="nodelet" name="estimation_standalone_nodelet"  args="manager" output="screen"/>
Nit: maybe the convention we can follow is `<function>_nodelet_manager`. So this one would be `interface_nodelet_manager`.

2024-03-29 18:36 UTC, aravindsiv commented on estimation/launch/nodelets_as_nodes.launch
Can we have this `.launch` file use the same `roslaunch` params as the nodelet's `.launch` file? That way, when we are debugging, we change only a single file to reproduce.

2024-03-29 18:36 UTC, aravindsiv commented on infrastructure/utils/launch/nodelet_debug.launch
Why is this file here? Isn't this logic part of a larger `roslaunch` file?

2024-04-08 15:58 UTC, garygra commented on estimation/launch/nodelets_as_nodes.launch
Removing this file to have only the debug one.

2024-04-08 16:02 UTC, garygra commented on infrastructure/utils/launch/nodelet_debug.launch
I used for debugging, removing it.

2024-04-08 16:13 UTC, aravindsiv requested changes
Minor comments to restore the nodelets debug example.

2024-04-08 16:13 UTC, aravindsiv commented on estimation/launch/nodelets_as_nodes.launch
We should keep one copy of this logic in a bigger `.launch` file, or move its contents to `nodelets_debug.launch`.

2024-04-15 19:56 UTC, aravindsiv approved these changes
LGTM, merging.

2024-04-15 19:56 UTC, merged