Mushr feedback control
PRX-Kinodynamic/mujoco_ros pull request #27
Opened 2024-03-29 18:24 UTC by aravindsiv

Adding a single feedback controller class that can use a controller implemented inside ML4KP.

2024-04-08 16:26 UTC, garygra reviewed
Need some changes because is not compiling as is.

2024-04-08 16:26 UTC, garygra commented on control/CMakeLists.txt
> +  include
No include directory, remove this line unless there is a missing file.

2024-04-08 16:26 UTC, garygra commented on control/src/nodelets/mushr_feedback_controller.cpp
> +    controller->set_goal(ml4kp_params["goal_state"].as<std::vector<double>>());
There is no templated set_goal in the main branch of ML4KP, is there a PR missing?

2024-04-08 16:26 UTC, garygra commented on control/src/nodelets/mushr_feedback_controller.cpp
> +    controller->reset();
Same as above, no reset on `ML4KP-devel`'s main

2024-04-08 16:26 UTC, garygra commented on control/src/nodelets/mushr_feedback_controller.cpp
> +    controller->get_control(current_state, current_control);
`get_control` is only defined for `mushr_pure_persuit`, not for the feedback controller.

2024-04-08 16:36 UTC, aravindsiv commented
Let me send a PR for `ML4KP-devel` to compile this PR by tonight.

2024-04-14 19:50 UTC, aravindsiv commented
[This PR](https://github.com/PRX-Kinodynamic/ML4KP-devel/pull/43) on `ML4KP-devel` should help with compiling this one.

2024-04-15 16:54 UTC, garygra requested changes
Minor problem on `control/CMakeLists.txt`. Otherwise is compiling.

2024-04-15 16:54 UTC, garygra commented on control/CMakeLists.txt
> + INCLUDE_DIRS include
Comment this out, no `include` dir on control/

2024-04-15 19:29 UTC, garygra reviewed
Removing INCLUDE_DIRS include

2024-04-15 19:30 UTC, garygra approved these changes

2024-04-15 19:30 UTC, merged