Changes easier compilation + minor extras:
PRX-Kinodynamic/mujoco_ros pull request #3
Opened 2023-10-17 19:20 UTC by garygra

* Find_packag'ing mujoco
 * Change directories mujoco -> mujoco_ros (+ includes)
 * gitignore top-level cmake + system-specific files

2023-10-27 22:16 UTC, garygra commented
Working on Ubuntu + Macos.

2023-10-30 14:04 UTC, aravindsiv requested changes
Just some minor comments.

2023-10-30 14:04 UTC, aravindsiv commented on README.md
> +cd MUJOCO/PATH
Nit: I prefer `/path/to/mujoco` to avoid confusion with environment variables like `$PATH`.

2023-10-30 14:04 UTC, aravindsiv commented on mujoco_ros/include/mujoco_ros/simulator.hpp
I think it would be a good idea to add your clang format file.

2023-10-30 22:23 UTC, aravindsiv approved these changes
LGTM, we can merge.

2023-10-30 22:23 UTC, merged